"""empty message

Revision ID: 5a2057d49b6f
Revises: 7065456f4e57
Create Date: 2023-03-10 13:58:46.967646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2057d49b6f'
down_revision = '7065456f4e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('current_price', sa.Float(asdecimal=True, decimal_return_scale=2), nullable=False),
    sa.Column('daily_change', sa.Float(asdecimal=True, decimal_return_scale=2), nullable=False),
    sa.PrimaryKeyConstraint('ticker'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['stocks.ticker'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('stocks')
    # ### end Alembic commands ###
